add release job

diff --git a/.github/workflows/node.yml b/.github/workflows/node.yml
--- a/.github/workflows/node.yml
+++ b/.github/workflows/node.yml
@@ -100,3 +100,48 @@ jobs:
     - name: Upload coverage to Codecov
       if: matrix.node == '16' && (github.event_name != 'push' || github.ref_type != 'tag' || !startsWith(github.ref_name, 'v'))
       uses: codecov/codecov-action@v3
+
+  release:
+    name: Upload Release Package
+    if: github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
+    needs:
+    - format
+    - lint
+    - test
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v3
+    - name: Set up NodeJS 16
+      uses: actions/setup-node@v3
+      with:
+        node-version: 16
+    - name: Install dependencies
+      run: npm ci
+    - name: Build package
+      run: npm pack
+    - name: Extract version from package.json
+      uses: sergeysova/jq-action@v2
+      id: version
+      with:
+        cmd: 'jq .version package.json -r'
+    - name: Check package version
+      run: |
+        version=$(echo ${{ github.ref_name }} | cut -c2-)
+        if test "${version}" = "${{ steps.version.outputs.value }}"; then
+          echo "version ok"
+        else
+          echo "Error: tag ${{ github.ref_name }} and package version ${version} do not match" 1>&2
+          exit 1
+        fi
+    - name: Upload binaries to release
+      uses: svenstaro/upload-release-action@v2
+      with:
+        repo_token: ${{ secrets.GITHUB_TOKEN }}
+        file: smartdcc-*tgz
+        file_glob: true
+        tag: ${{ github.ref }}
+        overwrite: true
+        body: "Release ${{ github.ref_name }}"
+    - uses: JS-DevTools/npm-publish@v1
+      with:
+        token: ${{ secrets.NPM_PUBLISH_TOKEN }}
